function cfg = generateBIDSFileName(cfg, dcm)
%% Generate empty parameters:
dataType = char();
dataModality = char();
taskName = char();
runNumber = char();
eventsFileName = char();
contextFileName = char();
direction = char();
echo = char();
acquisition = char();
reconstruction = char();
part = char();

%% Extract data information:
if isfield(dcm, 'dataType')
    dataType  = dcm.dataType;
end

if isfield(dcm, 'modality')
    dataModality  = dcm.modality;
end

if isfield(dcm, 'task')
    taskName  = ['task-' dcm.task];
end

if isfield(dcm, 'run')
    runNumber  = ['run-' dcm.run];
end

if isfield(dcm, 'dir')
    direction  = ['dir-' dcm.dir];
end

if isfield(dcm, 'echo')
    echo  = ['echo-' dcm.echo];
end

if isfield(dcm, 'acquisition')
    acquisition  = ['acq-' dcm.acquisition];
end

if isfield(dcm, 'reconstruction')
    reconstruction  = ['rec-' dcm.reconstruction];
end

if isfield(dcm, 'part')
    part  = ['part-' dcm.part];
end


%% Generate the file depending on dataType name:
% The BIDS standard defines a file naming structure that depends on the
% data type. We break down the modalities currently available in the
% tool.
% Note: When introducing a new parameter, check the order in which it
% must appear for each of the modalities.

if strcmp(dataType,'func')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        runNumber '_' ...
        echo '_' ...
        part '_'...
        dataModality];

    eventsFileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        runNumber '_' ...
        'events.tsv'];

elseif strcmp(dataType,'anat')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        runNumber '_' ...
        echo '_' ...
        part '_'...
        dataModality];

elseif strcmp(dataType,'fmap')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        echo];

elseif strcmp(dataType,'dwi')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        runNumber '_' ...
        part '_'...
        dataModality];

elseif strcmp(dataType,'mrs')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality];

elseif strcmp(dataType,'perf')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        runNumber '_' ...
        echo '_' ...
        part '_'...
        dataModality];

    contextFileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        runNumber '_' ...
        '_aslcontext.tsv'];

else

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        dataModality];

end

%% Delete duplicate caracters:
cfg.fileName = removeDuplicateChar(fileName,'_');
cfg.eventsFileName = removeDuplicateChar(eventsFileName,'_');
cfg.contextFileName = removeDuplicateChar(contextFileName,'_');

end