function cfg = generate_bids_filename(cfg, dcm)
%% Generate empty parameters:
data_type = char();
data_modality = char();
task_name = char();
run_number = char();
events_filename = char();
context_filename = char();
direction = char();
echo = char();
acquisition = char();
reconstruction = char();
part = char();
description = char();

%% Extract data information:
if isfield(dcm, 'data_type')
    data_type  = dcm.data_type;
end

if isfield(dcm, 'modality')
    data_modality  = dcm.modality;
end

if isfield(dcm, 'task')
    task_name  = ['task-' dcm.task];
end

if isfield(dcm, 'run')
    run_number  = ['run-' dcm.run];
end

if isfield(dcm, 'dir')
    direction  = ['dir-' dcm.dir];
end

if isfield(dcm, 'echo')
    echo  = ['echo-' dcm.echo];
end

if isfield(dcm, 'acquisition')
    acquisition  = ['acq-' dcm.acquisition];
end

if isfield(dcm, 'reconstruction')
    reconstruction  = ['rec-' dcm.reconstruction];
end

if isfield(dcm, 'part')
    part  = ['part-' dcm.part];
end

if isfield(dcm, 'desc')
    description  = ['desc-' dcm.desc];
end


%% Generate the file depending on dataType name:
% The BIDS standard defines a file naming structure that depends on the
% data type. We break down the modalities currently available in the
% tool.
% Note: When introducing a new parameter, check the order in which it
% must appear for each of the modalities.

if strcmp(data_type,'func')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        task_name '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        run_number '_' ...
        echo '_' ...
        part '_' ...
        description '_' ...
        data_modality];

    events_filename = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        task_name '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        run_number '_' ...
        'events.tsv'];

elseif strcmp(data_type,'anat')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        task_name '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        run_number '_' ...
        echo '_' ...
        part '_' ...
        description '_' ...
        data_modality];

elseif strcmp(data_type,'fmap')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        acquisition '_' ...
        direction '_' ...
        run_number '_' ...
        echo '_' ...
        part '_' ...
        description];

    % For EPI-type fieldmaps (used for TOPUP correction), the modality
    % suffix (epi) must be appended to the filename, since dcm2niix does
    % not rename the output for this case (as it does for phase-difference
    % fmaps with _ph/_e1/_e2 suffixes).
    if strcmp(data_modality,'epi')
        file_name = [file_name '_' data_modality];
    end

elseif strcmp(data_type,'dwi')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        run_number '_' ...
        part '_' ...
        description '_' ...
        data_modality];

elseif strcmp(data_type,'mrs')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        task_name '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        run_number '_' ...
        echo '_' ...
        description '_' ...
        data_modality];

elseif strcmp(data_type,'perf')

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        run_number '_' ...
        echo '_' ...
        part '_' ...
        description '_' ...
        data_modality];

    context_filename = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        acquisition '_' ...
        reconstruction '_' ...
        direction '_' ...
        run_number '_' ...
        '_aslcontext.tsv'];

else

    file_name = [...
        cfg.subject_id '_' ...
        cfg.session_id '_' ...
        description '_' ...
        data_modality];

end

%% Delete duplicate caracters:
cfg.file_name = remove_duplicate_char(file_name,'_');
cfg.events_filename = remove_duplicate_char(events_filename,'_');
cfg.context_filename = remove_duplicate_char(context_filename,'_');

end