function cfg = generateBIDSFileName(cfg, dcm)
%% Generate empty parameters:
dataType = char();
dataModality = char();
taskName = char();
runNumber = char();
eventsFileName = char();
contextFileName = char();
direction = char();
echo = char();
acquisition = char();

%% Extract data information:
if isfield(dcm, 'dataType')
    dataType  = dcm.dataType;
end

if isfield(dcm, 'modality')
    dataModality  = dcm.modality;
end

if isfield(dcm, 'task')
    taskName  = dcm.task;
end

if isfield(dcm, 'run')
    runNumber  = dcm.run;
end

if isfield(dcm, 'dir')
    direction  = dcm.dir;
end

if isfield(dcm, 'echo')
    echo  = dcm.echo;
end

if isfield(dcm, 'acquisition')
    acquisition  = dcm.acquisition;
end


%% Generate the file depending on dataType name:
% El estándar BIDS define una estructura a la hora de nombrar los archivos
% que depende del tipo de dato. Desglosamos las modalidades disponibles
% actualmente en la herramienta.
% Nota: En caso de introducir un nuevo parámetro revisar en que orden debe
% aparecer para cada una de las modalidades.

if strcmp(dataType,'func')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality];

    eventsFileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality '_' ...
        'events.tsv'];

elseif strcmp(dataType,'anat')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality];

elseif strcmp(dataType,'fmap')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        echo];

elseif strcmp(dataType,'dwi')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        dataModality];

elseif strcmp(dataType,'mrs')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        taskName '_' ...
        acquisition '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality];

elseif strcmp(dataType,'perf')

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        echo '_' ...
        dataModality];

    contextFileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        acquisition '_' ...
        direction '_' ...
        runNumber '_' ...
        '_aslcontext.tsv'];

else

    fileName = [...
        cfg.subjectId '_' ...
        cfg.sessionName '_' ...
        dataModality];

end

%% Delete duplicate caracters:
cfg.fileName = removeDuplicateChar(fileName,'_');
cfg.eventsFileName = removeDuplicateChar(eventsFileName,'_');
cfg.contextFileName = removeDuplicateChar(contextFileName,'_');

end